config/routes.rb
Rails.application.routes.draw do
  concern :voteable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :questions, concerns: [:voteable] do
    resources :comments, only: [:create], defaults: { commentable: 'questions' }
    resources :answers do
      patch 'set_as_best', on: :member
    end
  end

  resources :answers, concerns: [:voteable], only: [:vote_up, :vote_down, :vote_delete] do
    resources :comments, only: [:create], defaults: { commentable: 'answers' }
  end

  delete '/attachment/:id', to: 'attachments#destroy', as: :destroy_attachment

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  get '/confirmations/questionary/:user_id', to: 'confirmations#questionary_get', as: 'confirmation_questionary_get'
  post '/confirmations/questionary/:user_id', to: 'confirmations#questionary_post', as: 'confirmation_questionary_post'

  get '/confirmations/confirm/:token', to: 'confirmations#confirm', as: 'confirmation_confirm'

end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  belongs_to :user
  
  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def best_answer
    self.answers.bests.first
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: [:show]

  after_action :publish_question, only: [:create]

  def index
    respond_with(@questions = Question.all)
  end

  def show
    gon.question = @question
    respond_with @question
  end

  def new
    respond_with @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.create(question_params.merge(user: current_user))
    respond_with @question
  end

  def update
    if current_user.author_of?(@question)
      if @question.update(question_params)
        flash.now[:notice] = 'Your question was succesfully updated'
      else
        flash.now[:alert] = 'Error while creating question'
      end
    else
      flash.now[:alert] = 'You dont have enough privilege'
    end
  end

  def destroy
    if current_user.author_of?(@question)
      respond_with @question.destroy
    else
      flash[:alert] = 'You dont have enough privilege'
      render :show
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def build_answer
    @answer = @question.answers.new
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
.question_content
  .question_title
    =link_to question.title, question_path(question)
  .question_body
    =question.body

app/views/questions/index.html.slim
.questions_wrapper
  =render @questions

app/views/questions/new.html.slim
-if @question.errors
  .validation_errors
    -@question.errors.full_messages.each do |msg|
      p=msg

=form_for @question do |f|
  =f.label :title
  =f.text_field :title
  br
  =f.label :body
  =f.text_area :body
  br
  p Attachments:
  p
    =f.fields_for :attachments, @question.attachments.build do |attach|
      p= render 'share/attachment_fields', f: attach
      p= link_to_add_association 'add file', f, :attachments, partial: 'share/attachment_fields'
  =f.submit 'Create'

app/views/questions/show.html.slim
-if @answer&.errors
  .validation_errors
    -@answer.errors.full_messages.each do |msg|
      p =msg
div
  .container
    .col-lg-6
      .question_vote_nav
        =render 'share/vote_nav', obj: @question
      p.question_title.h2 =@question.title
  .container
    .col-lg-6
      p.question_body =@question.body
    -if current_user&.author_of?(@question)
      p =link_to 'delete question', question_path(@question), method: :delete
      p =link_to 'Edit question','', class: 'edit_question_link'
      .edit_question_form
        =form_for @question, remote: true, method: :patch  do |f|
          .container
            .form-group.col-lg-6
              =f.label :title, 'new title'
              =f.text_field :title, class: 'form-control'
          .container
            .form-group.col-lg-6
              =f.label :body, 'new body'
              =f.text_area :body, class: 'form-control', rows: 5
          .container
            .col-lg-6.form-group
              =f.fields_for :attachments, @question.attachments.build do |attach|
                p= render 'share/attachment_fields', f: attach
                p= link_to_add_association 'add file', f, :attachments, partial: 'share/attachment_fields'
              .form-group
                =f.submit 'Save', class: 'btn btn-primary'
  div.q_attachments_wrapper
    ul.q_attachments_container
      = render 'share/attachments', obj: @question
  .container.question_comments data-id=@question.id
    p.h4 Comments:
    .container.comments_container
      = render @question.comments.order(created_at: :asc)
    -if current_user
      = render 'share/comment_form', commentable: @question
  .container
    p.h4 Answers:
    hr.col-lg-8
  .answers_container
    =render @question.answers.order(is_best: :desc , created_at: :asc)

-if current_user
  .container
    =form_for [@question, @answer], method: :post, remote: true do |f|
      .row
        .col-lg-6.form-group
          =f.label :body, 'Your answer'
          =f.text_area :body,class: 'form-control', rows: 5
      .row
        .col-lg-6
          =f.fields_for :attachments, @answer.attachments.build do |attach|
            p= render 'share/attachment_fields', f: attach
            p= link_to_add_association 'add file', f, :attachments, partial: 'share/attachment_fields'
      .row
        =f.submit 'Add answer', class: 'btn btn-primary'

app/views/questions/update.js.erb
$('.noty_wrapper').html("<%= j render 'share/noty' %>")
$('.validation_errors').val('');
<% if @question.errors.present? %>
  $('.validation_errors').html("<%= @question.errors.full_messages.join('<br') %>");
<% else %>
  $(".question_title").html('<%= j @question.title %>');
  $(".question_body").html('<%= j @question.body %>');
  $(".edit_question_form").hide();
  $(".edit_question_link").show();
  $('.q_attachments_container ').html('<%= j render "share/attachments", obj: @question %>')
  
<% end %>