config/routes.rb
Rails.application.routes.draw do
  concern :voteable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :questions, concerns: [:voteable] do
    resources :comments, only: [:create], defaults: { commentable: 'questions' }
    resources :answers do
      patch 'set_as_best', on: :member
    end
  end

  resources :answers, concerns: [:voteable], only: [:vote_up, :vote_down, :vote_delete] do
    resources :comments, only: [:create], defaults: { commentable: 'answers' }
  end

  delete '/attachment/:id', to: 'attachments#destroy', as: :destroy_attachment

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  get '/confirmations/questionary/:user_id', to: 'confirmations#questionary_get', as: 'confirmation_questionary_get'
  post '/confirmations/questionary/:user_id', to: 'confirmations#questionary_post', as: 'confirmation_questionary_post'

  get '/confirmations/confirm/:token', to: 'confirmations#confirm', as: 'confirmation_confirm'

end

app/views/share/_attachment_fields.html.slim
.nested-fields
  p= f.label :file
  p= f.file_field :file

  p= link_to_remove_association "delete file", f

app/views/share/_attachments.html.slim
-obj.attachments.each do |a|
  -if a.persisted?
    .attachment data-id=a.id
      li =link_to a.file.file.filename, a.file.url 
      -if current_user&.author_of?(obj)
        li =link_to 'delete attach', destroy_attachment_path(a), method: :delete, remote: true
  

app/views/share/_comment_form.html.slim
.container.comment_form_container
  - @comment ||= commentable.comments.build
  = form_for [commentable, @comment], method: :post, remote: true do |f|
    .row
      col-lg-6.form-group
        =f.label :body, 'Your comment'
        =f.text_area :body, class: 'form-control', rows: 3
      col-lg-6.form-group
        =f.submit 'Add comment', class: 'btn btn-primary'

app/views/share/_noty.html.slim
= bootstrap_flash

app/views/share/_vote_nav.html.slim
p.total_votes data-id=obj.id 
  =obj.votes.total_count
-if current_user && !current_user.author_of?(obj)
  p.vote_up.vote 
    =link_to 'vote_up', polymorphic_path([:vote_up, obj]), method: :post, remote: true
  p.vote_down.vote 
    =link_to 'vote_down', polymorphic_path([:vote_down, obj]), method: :post, remote: true
  p.vote_delete.vote 
    =link_to 'vote_delete', polymorphic_path([:vote_delete, obj]), method: :delete, remote: true