config/routes.rb
Rails.application.routes.draw do
  concern :voteable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :questions, concerns: [:voteable] do
    resources :comments, only: [:create], defaults: { commentable: 'questions' }
    resources :answers do
      patch 'set_as_best', on: :member
    end
  end

  resources :answers, concerns: [:voteable], only: [:vote_up, :vote_down, :vote_delete] do
    resources :comments, only: [:create], defaults: { commentable: 'answers' }
  end

  delete '/attachment/:id', to: 'attachments#destroy', as: :destroy_attachment

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  get '/confirmations/questionary/:user_id', to: 'confirmations#questionary_get', as: 'confirmation_questionary_get'
  post '/confirmations/questionary/:user_id', to: 'confirmations#questionary_post', as: 'confirmation_questionary_post'

  get '/confirmations/confirm/:token', to: 'confirmations#confirm', as: 'confirmation_confirm'

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachmentable, dependent: :destroy
  validates  :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :bests, -> { where(is_best: true) }
  
  def set_best
    self.transaction do 
      self.question.answers.update_all(is_best: false)
      self.update!(is_best: true)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [:create, :destroy, :update, :set_as_best]

  after_action :publish_answer, only: [:create]

  respond_to :js
  respond_to :json, only: :create

  def edit
    answer
  end

  def create
    @answer = question.answers.create(answer_params.merge(user: current_user))
    respond_with @answer
  end

  def update
    if current_user.author_of?(answer)
      answer.update(answer_params)
      respond_with answer
    else
      flash.now[:alert] = 'You dont have enough privilege'
    end
  end

  def destroy
    if current_user.author_of?(answer)
      respond_with answer.destroy
    else
      flash.now[:alert] = 'You dont have enough privilege'
    end
  end

  def set_as_best
    if current_user.author_of?(question) && question.answers.include?(answer)
      answer.set_best
      flash.now[:notice] = 'Answer set as best'
    else
      flash.now[:alert] = 'You dont have enough privilege'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "question_#{@question.id}",
      @answer.to_json(include: :attachments)
      )
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
-if answer.persisted?
  .answer.container data={answer_id:answer.id} class=(answer.is_best ? 'best_answer' : '')
    .row
      .answer_vote_nav
        =render 'share/vote_nav', obj: answer
      .answer_body.col-lg-6 data={answer_id:answer.id} 
        p=answer.body
      ul.a_attachments_container
        = render 'share/attachments', obj: answer
      .links.col-lg-4
        -if current_user&.author_of?(answer)
            .edit_answer
              =link_to 'Edit','', data: { edit_answer_link_id: answer.id }, class: 'edit_answer_link'
            .delete_answer
              =link_to 'delete answer', question_answer_path(@question, answer), method: :delete, class: 'delete_answer', remote: true, data: {answer_id: answer.id}
        -if current_user&.author_of?(@question)
          p =link_to 'Mark as best', set_as_best_question_answer_path(@question, answer), remote: true, method: :patch
        .edit_answer_form id="edit_answer_form_#{answer.id}"
          =form_for [@question, answer], remote: true, method: :patch  do |f|
            .container
              .col-lg-6.form-group
                =f.label :body, 'Answer'
                =f.text_area :body, id: "edit_answer_body_#{answer.id}", class: 'form-control'
            .container
              .col-lg-6
                .form-group
                  =f.fields_for :attachments do |attach|
                    p= render 'share/attachment_fields', f: attach
                    p= link_to_add_association 'add file', f, :attachments, partial: 'share/attachment_fields'
                .form-group
                  =f.submit 'Save', class: 'btn btn-primary'
    .row.answer_comments data-id=answer.id
      p.h4 Comments:
      .container.comments_container
        = render answer.comments.order(created_at: :asc)
      -if current_user
        = render 'share/comment_form', commentable: answer        
    .row
      hr.col-lg-8
          

app/views/answers/_attachment_fields.html.slim
.nested-fields
  p= f.label :file
  p= f.file_field :file
  p= link_to_remove_association "delete file", f

app/views/answers/create.js.erb
$('.noty_wrapper').html("<%= j render 'share/noty' %>")
$('.validation_errors').val('');
<% if @answer.errors.present? %>
  $('.validation_errors').html("<%= @answer.errors.full_messages.join('<br') %>");
<% else %>
  $('.answers_container').append('<%= j render @answer %>');
  $('textarea#answer_body').val('');
  $("#edit_answer_form_"+<%= @answer.id %>).hide();
  $('#new_answer .nested-fields').remove();
<% end %>

app/views/answers/destroy.js.erb
$('.noty_wrapper').html("<%= j render 'share/noty' %>")
<% unless @answer.persisted? %>
  $(".answer[data-answer-id=<%= @answer.id %>]").remove();
<% end %>

app/views/answers/set_as_best.js.erb
$('.noty_wrapper').html("<%= j render 'share/noty' %>")
$('.answer').removeClass('best_answer');
$('.answer[data-answer-id=<%= @answer.id%>]').addClass('best_answer');

app/views/answers/update.js.erb
$('.noty_wrapper').html("<%= j render 'share/noty' %>")
$('.validation_errors').val('');
<% if @answer.errors.present? %>
  $('.validation_errors').html("<%= @answer.errors.full_messages.join('<br') %>");
<% else %>
  $(".answer_body[data-answer-id='<%= @answer.id.to_s %>']").html('<%= j @answer.body %>');
  $("#edit_answer_form_"+<%= @answer.id %>).hide();
  $(".edit_answer_link[data-edit-answer-link-id=<%= @answer.id %>]").show();
  $('.q_attachments_container ').html('<%= j render "share/attachments", obj: @answer %>')
<% end %>