config/routes.rb
Rails.application.routes.draw do
  concern :voteable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_delete
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :questions, concerns: [:voteable] do
    resources :comments, only: [:create], defaults: { commentable: 'questions' }
    resources :answers do
      patch 'set_as_best', on: :member
    end
  end

  resources :answers, concerns: [:voteable], only: [:vote_up, :vote_down, :vote_delete] do
    resources :comments, only: [:create], defaults: { commentable: 'answers' }
  end

  delete '/attachment/:id', to: 'attachments#destroy', as: :destroy_attachment

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  get '/confirmations/questionary/:user_id', to: 'confirmations#questionary_get', as: 'confirmation_questionary_get'
  post '/confirmations/questionary/:user_id', to: 'confirmations#questionary_post', as: 'confirmation_questionary_post'

  get '/confirmations/confirm/:token', to: 'confirmations#confirm', as: 'confirmation_confirm'

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Thinknetika17"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all", 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    = Gon::Base.render_data
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/"Thinknetika17
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li = link_to 'Ask question', new_question_path
              -if current_user
                li= link_to "Sign out", destroy_user_session_path, method: :delete
              -else
                li= link_to  'Sign up', new_user_registration_path

    .container
      .row
        .col-lg-9
          .noty_wrapper
            = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Placeholder

      footer
        p &copy; https://github.com/p0m1d0rka/thinknetika17